/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_device_name                    3
#define gattdb_command                        8
#define gattdb_distance_left                  10
#define gattdb_distance_right                 13
#define gattdb_distance_front                 16


#endif // __GATT_DB_H
